//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace php_soap_server.PhpServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bflm.eu/php-soap-server/soap.php", ConfigurationName="PhpServer.SoapClassPort")]
    public interface SoapClassPort {
        
        // CODEGEN: Parameter 'getDateTimeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bflm.eu/php-soap-server/soap.php#getDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        php_soap_server.PhpServer.getDateTimeResponse getDateTime(php_soap_server.PhpServer.getDateTimeRequest request);
        
        // CODEGEN: Parameter 'getHashResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bflm.eu/php-soap-server/soap.php#getHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        php_soap_server.PhpServer.getHashResponse getHash(php_soap_server.PhpServer.getHashRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDateTime", WrapperNamespace="http://bflm.eu/php-soap-server/soap.php", IsWrapped=true)]
    public partial class getDateTimeRequest {
        
        public getDateTimeRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDateTimeResponse", WrapperNamespace="http://bflm.eu/php-soap-server/soap.php", IsWrapped=true)]
    public partial class getDateTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bflm.eu/php-soap-server/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getDateTimeResult;
        
        public getDateTimeResponse() {
        }
        
        public getDateTimeResponse(string getDateTimeResult) {
            this.getDateTimeResult = getDateTimeResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bflm.eu/php-soap-server/soap.php")]
    public partial class HashResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hashField;
        
        private string createdByField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string createdBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("createdBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHash", WrapperNamespace="http://bflm.eu/php-soap-server/soap.php", IsWrapped=true)]
    public partial class getHashRequest {
        
        public getHashRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHashResponse", WrapperNamespace="http://bflm.eu/php-soap-server/soap.php", IsWrapped=true)]
    public partial class getHashResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bflm.eu/php-soap-server/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public php_soap_server.PhpServer.HashResponse getHashResult;
        
        public getHashResponse() {
        }
        
        public getHashResponse(php_soap_server.PhpServer.HashResponse getHashResult) {
            this.getHashResult = getHashResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SoapClassPortChannel : php_soap_server.PhpServer.SoapClassPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SoapClassPortClient : System.ServiceModel.ClientBase<php_soap_server.PhpServer.SoapClassPort>, php_soap_server.PhpServer.SoapClassPort {
        
        public SoapClassPortClient() {
        }
        
        public SoapClassPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapClassPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapClassPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapClassPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        php_soap_server.PhpServer.getDateTimeResponse php_soap_server.PhpServer.SoapClassPort.getDateTime(php_soap_server.PhpServer.getDateTimeRequest request) {
            return base.Channel.getDateTime(request);
        }
        
        public string getDateTime() {
            php_soap_server.PhpServer.getDateTimeRequest inValue = new php_soap_server.PhpServer.getDateTimeRequest();
            php_soap_server.PhpServer.getDateTimeResponse retVal = ((php_soap_server.PhpServer.SoapClassPort)(this)).getDateTime(inValue);
            return retVal.getDateTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        php_soap_server.PhpServer.getHashResponse php_soap_server.PhpServer.SoapClassPort.getHash(php_soap_server.PhpServer.getHashRequest request) {
            return base.Channel.getHash(request);
        }
        
        public php_soap_server.PhpServer.HashResponse getHash() {
            php_soap_server.PhpServer.getHashRequest inValue = new php_soap_server.PhpServer.getHashRequest();
            php_soap_server.PhpServer.getHashResponse retVal = ((php_soap_server.PhpServer.SoapClassPort)(this)).getHash(inValue);
            return retVal.getHashResult;
        }
    }
}
